spring:
  flyway:
    table: flyway_schema_history_client
    baseline-on-migrate: true
    baseline-version: 0
  datasource:
    url: jdbc:postgresql://postgres-deal:5432/${POSTGRES_DEAL_DB:deal_db}
    username: ${POSTGRES_DEAL_USER:deal_user}
    password: ${POSTGRES_DEAL_PASSWORD:deal_pass}
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8080

management:
  zipkin:
    tracing:
      endpoint: http://jaeger:14268/api/traces   # Jaeger collector (Zipkin format)

logging:
  logstash:
    encoder:
      destination: "logstash:5000"